### ISSUE TITLE
The psm1 uses powershell instead of pwsh

### ISSUE THREAD

**Issue by kusuriya** [exactmike/OneShell#13]
Just opening an issue for my pull request #12 , pwsh is the new name for powershell core and the name of the supported production binary on *nix systems. The new name should be embraced to make sure the module is not broken going forward.

Nice presentation at the summit BTW.

**Comment by exactmike** [comment]
Thanks for the catch!  Supporting running this module in PowerShell Core on Linux is hopefully in our future.
